amcl:
  ros__parameters:
    use_sim_time: True                 # Use simulation/ROS time

    # Robot frames
    base_frame_id: "base_footprint"    # Robot's base frame
    global_frame_id: "map"             # Frame localization is performed in
    odom_frame_id: "odom"              # Frame odometry is published in

    # Laser model parameters
    laser_model_type: "likelihood_field" # Common laser model
    laser_likelihood_max_dist: 2.0     # Max distance for likelihood calculation
    laser_max_range: 100.0             # Max laser range to consider (-1.0 = use sensor default)
    laser_min_range: -1.0              # Min laser range to consider (-1.0 = use sensor default)
    max_beams: 60                      # Max laser beams to use from scan
    sigma_hit: 0.2                     # Std dev for likelihood_field model
    z_hit: 0.5                         # Weight for z_hit part of laser model
    z_max: 0.05                        # Weight for z_max part of laser model
    z_rand: 0.5                        # Weight for z_rand part of laser model
    z_short: 0.05                      # Weight for z_short part of laser model

    # Odometry model parameters (tune based on robot's motion noise)
    alpha1: 0.2                        # Noise from rotation controller acting on rotation
    alpha2: 0.2                        # Noise from rotation controller acting on translation
    alpha3: 0.2                        # Noise from translation controller acting on translation
    alpha4: 0.2                        # Noise from translation controller acting on rotation
    alpha5: 0.2                        # Noise from translation controller (only if model is omni)

    # Particle filter parameters
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false                 # Whether to skip beams in likelihood calc
    lambda_short: 0.1
    max_particles: 8000                # Max number of particles
    min_particles: 200                 # Min number of particles
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0           # Exp filter decay rate for recovery (0=disabled)
    recovery_alpha_slow: 0.0           # Exp filter decay rate for recovery (0=disabled)
    resample_interval: 1               # Number of filter updates between resampling

    # Other parameters
    robot_model_type: "nav2_amcl::DifferentialMotionModel" # Motion model type
    save_pose_rate: 0.5                # Rate to publish estimated pose (-1.0 = disabled)
    tf_broadcast: true                 # Publish map->odom transform
    transform_tolerance: 1.0           # Time tolerance for TF lookups

    # Update rates
    update_min_a: 0.2                  # Min angular distance before filter update
    update_min_d: 0.25                 # Min translational distance before filter update

    # Initial pose (can be overridden by RViz or topic)
    set_initial_pose: true             # Use initial_pose from params if true
    initial_pose:
      x: -4.44264                     # Example initial pose x
      y: 2.32243                      # Example initial pose y
      z: 0.0
      yaw: 0.328028                   # Example initial pose yaw