behavior_server: # Note: This node used to be called recovery_server
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw # Topic for local costmap data
    footprint_topic: local_costmap/published_footprint # Topic for robot footprint
    cycle_frequency: 10.0 # Frequency for behavior server loop
    behavior_plugins: ["spin", "backup", "wait"] # Available recovery behaviors
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    # Common parameters for recoveries
    global_frame: odom # Frame recoveries operate in (often odom)
    robot_base_frame: base_link # MUST MATCH OTHER CONFIGS AND TF (e.g., base_footprint)
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    # Specific params for some recoveries (example for BackUp)
    # backup:
    #   speed: -0.15
    #   dist: 0.30
    # Specific params for Spin
    # spin:
    #   simulated_duration: 1.0
    max_rotational_vel: 1.0 # Max rotation speed for spin/backup
    min_rotational_vel: 0.4 # Min rotation speed for spin/backup
    rotational_acc_lim: 3.2 # Rotational acceleration limit